name: Release

# This job will only be triggered when a tag is pushed.
on:
  push:
    tags:
    - '*'
    branches:
    - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Generate the release notes
        uses: fgksgf/DeepRelease@master
        with:
          repo: 'apache/skywalking-python'
          debug: 'True'

      - name: Check the file
        run: cat release-notes.md
      
      - name: Generate the release notes
        uses: fgksgf/DeepRelease@master
        with:
          repo: 'apache/skywalking'
          debug: 'True'

      - name: Check the file
        run: cat release-notes.md